version: "3"
services:
  golang1.21.5-alpine3.18:
    stdin_open: true
    tty: true
    container_name: test1
    environment:
      - APPID=appid
      - KEY=key
    volumes:
      - /d/git/ytdlp:/data
    image: ytdlp:v1
    command: ash